services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=pass
    # - MONGO_INITDB_DATABASE=auth    (MongoDB irá criar um banco de dados com o nome "auth" quando o contêiner for iniciado pela primeira vez)
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=daniel
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}

# Acessar: http://localhost:8081/
# username: admin
# password: pass