version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mynet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ports:
      - "8081:8081"
    networks:
      - mynet

networks:
  mynet:
